### ISSUE TITLE
VM doesn't start - permission denied to move folder

### ISSUE THREAD

**Issue by Ags-saltillo** [VictoriaMetrics/helm-charts#459]
AKS: v1.24.6
VM Single: v1.86.2

I want to upgrade VM from 1.75.0 to 1.86.2, but when pod start give me this error:

`2023-01-30T14:24:04.620Z	panic	VictoriaMetrics/lib/fs/fs.go:237	FATAL: cannot move /victoria-metrics-data/data/small/2023_01/16772_16772_20230130141920.176_20230130141927.660_173F1BF07C75A679 to /victoria-metrics-data/data/small/2023_01/16772_16772_20230130141920.176_20230130141927.660_173F1BF07C75A679.must-remove.1675088560992895650: rename /victoria-metrics-data/data/small/2023_01/16772_16772_20230130141920.176_20230130141927.660_173F1BF07C75A679 /victoria-metrics-data/data/small/2023_01/16772_16772_20230130141920.176_20230130141927.660_173F1BF07C75A679.must-remove.1675088560992895650: permission denied
panic: FATAL: cannot move /victoria-metrics-data/data/small/2023_01/16772_16772_20230130141920.176_20230130141927.660_173F1BF07C75A679 to /victoria-metrics-data/data/small/2023_01/16772_16772_20230130141920.176_20230130141927.660_173F1BF07C75A679.must-remove.1675088560992895650: rename /victoria-metrics-data/data/small/2023_01/16772_16772_20230130141920.176_20230130141927.660_173F1BF07C75A679 /victoria-metrics-data/data/small/2023_01/16772_16772_20230130141920.176_20230130141927.660_173F1BF07C75A679.must-remove.1675088560992895650: permission denied

goroutine 44 [running]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logMessage({0xb6c582, 0x5}, {0xc001f64b40, 0x224}, 0x3?)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:281 +0xa9d
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevelSkipframes(0x1, {0xb6c582, 0x5}, {0xb7f58b?, 0x2?}, {0xc0138f7888?, 0xc0138f7858?, 0x0?})
	github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:138 +0x1d6
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevel(...)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:130
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.Panicf(...)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:126
github.com/VictoriaMetrics/VictoriaMetrics/lib/fs.MustRemoveDirAtomic({0xc018b9c000, 0x6c})
	github.com/VictoriaMetrics/VictoriaMetrics/lib/fs/fs.go:237 +0x1d0
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.runTransaction(0xc0160e4680?, {0xc00002b230, 0x29}, {0xc00002b260, 0x27}, {0xc0160e4680, 0x3e})
	github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:2084 +0x825
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).openCreatedPart(0xc00010c300, 0xc000e4f2f0, {0xc0130f3e00?, 0xf, 0x10}, 0x0, {0xc00002b230, 0x29}, {0xc00dc80e40, 0x3e}, ...)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:1515 +0x3c5
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).mergeParts(0xc00010c300, {0xc0130f3e00, 0xf, 0x10}, 0xc000a0cf00?, 0x0)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:1346 +0x9e7
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).mergeExistingParts(0xc00010c300, 0x48?)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:1187 +0x388
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).mergeWorker(0xc00010c300)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:1059 +0x65
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).startMergeWorkers.func1()
	github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:1046 +0x25
created by github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).startMergeWorkers
	github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:1045 +0x37`

VM has a persistent storage on  Azure Blob Storage. if a rollback to previous version of VM (v.175.0), it's start correcty.
I have tried with previous versions (v1.86.0, v1.86.1) and we have the same issue. What has changed to be able to access the storage correctly?

**Comment by Ags-saltillo** [comment]
this error does not go here, my mistake
