### ISSUE TITLE
vmagent psp policy / runAsNonRoot

### ISSUE THREAD

**Issue by paprickar** [VictoriaMetrics/helm-charts#52]
Hey,

it seems that vmagent can`t run in clusters with PSP enabled.

If I want to run the vmagent it is not possible as kubernetes detect it is running as root.

If I set following then the pod is able / allowed to start
```
securityContext:
  runAsNonRoot: true
```
https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-agent/values.yaml#L59

But then vmagent does not work properly. It seems that vmagent need to persist a queue on disk.

```
...
020-07-22T16:49:14.059Z        info    VictoriaMetrics/lib/logger/flag.go:20   flag "remoteWrite.urlRelabelConfig" = ""
2020-07-22T16:49:14.059Z        info    VictoriaMetrics/lib/logger/flag.go:20   flag "tls" = "false"
2020-07-22T16:49:14.059Z        info    VictoriaMetrics/lib/logger/flag.go:20   flag "tlsCertFile" = ""
2020-07-22T16:49:14.059Z        info    VictoriaMetrics/lib/logger/flag.go:20   flag "tlsKeyFile" = "secret"
2020-07-22T16:49:14.059Z        info    VictoriaMetrics/lib/logger/flag.go:20   flag "version" = "false"
2020-07-22T16:49:14.059Z        info    VictoriaMetrics/app/vmagent/main.go:77  starting vmagent at ":8429"...
2020-07-22T16:49:14.062Z        info    VictoriaMetrics/lib/memory/memory.go:35 limiting caches to 4898832384 bytes, leaving 3265888256 bytes to the OS according to -memory.allowedPercent=60
2020-07-22T16:49:14.062Z        error   VictoriaMetrics/lib/persistentqueue/persistentqueue.go:146      cannot open persistent queue at "vmagent-remotewrite-data/persistent-queue/696B6E463EF121CC": cannot create directory "vmagent-remotewrite-data/persistent-queue/696B6E463EF121CC": mkdir vmagent-remotewrite-data: permission denied; cleaning it up and trying again
2020-07-22T16:49:14.062Z        panic   VictoriaMetrics/lib/persistentqueue/persistentqueue.go:150      FATAL: cannot create directory "vmagent-remotewrite-data/persistent-queue/696B6E463EF121CC": mkdir vmagent-remotewrite-data: permission denied
panic: FATAL: cannot create directory "vmagent-remotewrite-data/persistent-queue/696B6E463EF121CC": mkdir vmagent-remotewrite-data: permission denied

goroutine 1 [running]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logMessage(0xac7d32, 0x5, 0xc0001961b0, 0x8e, 0x4)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:191 +0xa72
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevelSkipframes(0x1, 0xac7d32, 0x5, 0xacb2b2, 0x9, 0xc00011fb90, 0x1, 0x1)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:124 +0xd0
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevel(...)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:116
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.Panicf(...)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:112
github.com/VictoriaMetrics/VictoriaMetrics/lib/persistentqueue.mustOpen(0xc0001a0040, 0x3a, 0x7ffdfcd53b94, 0x6c, 0x20000080, 0x2000000, 0x0, 0xc00019c000)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/persistentqueue/persistentqueue.go:150 +0x367
github.com/VictoriaMetrics/VictoriaMetrics/lib/persistentqueue.MustOpen(...)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/persistentqueue/persistentqueue.go:134
github.com/VictoriaMetrics/VictoriaMetrics/lib/persistentqueue.MustOpenFastQueue(0xc0001a0040, 0x3a, 0x7ffdfcd53b94, 0x6c, 0xc8, 0x0, 0x3a)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/persistentqueue/fastqueue.go:40 +0x92
github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/remotewrite.newRemoteWriteCtx(0x0, 0x7ffdfcd53b94, 0x6c, 0xc8, 0xc00019a050, 0xc, 0xc)
        github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/remotewrite/remotewrite.go:171 +0x19b
github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/remotewrite.Init()
        github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/remotewrite/remotewrite.go:76 +0x2a3
main.main()
        github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/main.go:79 +0x370
```

**Comment by tenmozes** [comment]
please update agent helm chart to `0.4.9`
i was able to run agent with config

```
podSecurityContext:
  runAsUser: 1000 
  runAsNonRoot: true
containerWorkingDir: "/tmp"
```

**Comment by paprickar** [comment]
It works - thanks a lot
